### ISSUE TITLE
Searchable item type failing when selected

### ISSUE THREAD

**Issue by flxsource** [ryangjchandler/filament-navigation#17] opened 2022-06-13 20:26 UTC
When creating a navigation item with a searchable item type, selecting the type throws an Alpine error, and displays an empty, unstyled select element. If saved without selecting a target, the select element works correctly upon reopening the modal. Changing the item type after that point doesn't cause a problem either.

![image](https://user-images.githubusercontent.com/1785446/173438468-29e420f1-82a5-40b0-9bed-a15044584900.png)

<details>
<summary>Error</summary>

```
module.esm.js:416 Alpine Expression Error: Cannot read properties of null (reading 'target')

Expression: "selectFormComponent({
                        getOptionLabelUsing: async () => {
                            return await $wire.getSelectOptionLabel('mountedActionData.data.target')
                        },
                        getOptionLabelsUsing: async () => {
                            return await $wire.getSelectOptionLabels('mountedActionData.data.target')
                        },
                        getOptionsUsing: async () => {
                            return await $wire.getSelectOptions('mountedActionData.data.target')
                        },
                        getSearchResultsUsing: async (search) => {
                            return await $wire.getSelectSearchResults('mountedActionData.data.target', search)
                        },
                        isAutofocused: false,
                        isMultiple: false,
                        hasDynamicOptions: true,
                        hasDynamicSearchResults: false,
                        loadingMessage: 'Loading...',
                        maxItems: null,
                        noSearchResultsMessage: 'No options match your search.',
                        options: JSON.parse(atob('eyJhYm91dCI6IkFib3V0IiwiYm9va2luZ3MiOiJCb29raW5ncyIsImNvbnRhY3QiOiJDb250YWN0IiwiZWR1Y2F0aW9uIjoiRWR1Y2F0aW9uIiwiaG9tZSI6IkhvbWUgUGFnZSIsInBvcGVyYSI6IlBvcGVyYSIsInNob3dzIjoiU2hvd3MiLCJzb2NpYWwtcHJlc2NyaWJpbmciOiJTb2NpYWwgUHJlc2NyaWJpbmcifQ==')),
                        placeholder: 'Select an option',
                        searchingMessage: 'Searching...',
                        searchPrompt: 'Start typing to search...',
                        state: $wire.entangle('mountedActionData.data.target').defer,
                    })"
```

</details>

**Comment by flxsource** [comment] 2022-06-13 20:29
Just realised this is a duplicate of #15 (the phrasing it as a question threw me), closing this in favour of that issue.

**Comment by ryangjchandler** [comment] 2022-06-13 20:55
Duplicate of #15, please track there.

**Closed by ryangjchandler** 2022-06-13 20:55 UTC
